name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile:
    runs-on: self-hosted
    steps:

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make net-tools

      - name: Compile project
        working-directory: ../../../../
        run: |
          make all
  
  # unit_tests:
  #   runs-on: ubuntu-latest
  #   needs: compile
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up JDK
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '11'

  #     - name: Install dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y make net-tools sqlite3

  #     - name: Run unit tests
  #       run: make tests