name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile:
    runs-on: self-hosted
    steps:

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make net-tools

      - name: Compile project
        working-directory: ../../../../
        run: |
          make build-no-tests
  
  unit_tests:
    runs-on: self-hosted
    needs: compile
    steps:

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make net-tools sqlite3

      - name: Run unit tests
        working-directory: ../../../../
        run: |
          make tests